### ISSUE TITLE
Bad link in README

### ISSUE THREAD

**Issue by smalyshev** [CVEProject/cvelist#1843]
In the README, the link from CVE List leads to https://cve.mitre.org/cve/cve.html which is a 404.

**Comment by iamleot** [comment]
At least according web.archive.org it seems that this can be probably substituted with just 
<https://cve.mitre.org/cve/>

 <https://web.archive.org/web/20171219014329/http://cve.mitre.org/cve/cve.html>
 <https://web.archive.org/web/20151222104819/http://cve.mitre.org/cve/cve.html>

**Comment by cve-team** [comment]
Thank you for pointing this out. The links in the README have been repaired. 

Respectfully,
The CVE Assignment Team
