### ISSUE TITLE
quoting of cvss score values?

### ISSUE THREAD

**Issue by kurtseifried** [CVEProject/cvelist#291]
Was just looking at some cvss scores, shouldn't the score be quoted, e.g.:

         "baseScore" : 6.5,

because later on it is quoted:

         "version" : "3.0"

or does the score count as a number, but the version of cvss...  counts as a string?

**Comment by theall38103** [comment]
I see the CVSS version simply as a string that identifies the type of scoring info. Presumably we'll treat it as an enumeration in the schema. 

I see a CVSS score as a number, one that can be calculated from the associated metrics, that can fall anywhere within a range of values, that can be grouped together or compared, etc. Presumably we'll want to specify a range for it in the schema. 

Thoughts?

George

**Comment by kurtseifried** [comment]
Agreed, closing issue.
